try pure bash implementation instead

diff --git a/bin/xscreensaver-pi-hdmi b/bin/xscreensaver-pi-hdmi
--- a/bin/xscreensaver-pi-hdmi
+++ b/bin/xscreensaver-pi-hdmi
@@ -1,66 +1,70 @@
-#!/usr/bin/perl
- 
-#check_screen_state.pl - perl script to monitor screen state, and turn HDMI on or off
-use strict;
-use warnings;
-use threads;
-use Thread::Queue;
-$|=1;
+#!/bin/bash
 
-my $counter=-1;
-#time in seconds
-#my $time_to_power_off_screen_s = 1200; #20 minutes
-my $time_to_power_off_screen_s = 30; #20 minutes
-my $hdmi_off_command = "/usr/lib/xscreensaver-pi-hdmi/hdmi-off";
-my $hdmi_on_command  = "/usr/lib/xscreensaver-pi-hdmi/hdmi-on";
+TEMPFILE=`tempfile --prefix=hdmi. --suffix=.pid`
+echo 0 > $TEMPFILE
 
-#code to run a shell command in a thread, and get output from it
-sub pipeCommand {
-    my $cmd = shift;
-    my $Q = new Thread::Queue;
-    async{
-        my $pid = open my $pipe, $cmd or die $!;
-        $Q->enqueue( $_ ) while <$pipe>;
-        $Q->enqueue( undef );
-    }->detach;
-    return $Q;
+interrupt_potential_sleeping_processes() {
+    SLEEP_PID=0
+    if [ -x $TEMPFILE ] ; then
+        SLEEP_PID=`cat $TEMPFILE`
+    fi
+    if [ "0" != "$SLEEP_PID" ] ; then
+        echo 0 > $TEMPFILE
+        kill $SLEEP_PID
+    fi
 }
 
-my $pipe = pipeCommand(
-    'xscreensaver-command -watch |'
-) or die;
 
-print_("Starting, waiting on input.\n");
-while( 1 ) {
-    if( $pipe->pending ) {
-        my $line = $pipe->dequeue or last;
-        print_("$line");
-      if ($line =~ m/^(BLANK|LOCK)/) {
-         $counter = $time_to_power_off_screen_s;
-      } elsif ($line =~ m/^UNBLANK/) {
-         if($counter <= 0){
-            print_( "turn on\n");
-            print_( `$hdmi_on_command `);
-         }else{
-            print_("screen already on\n");
-         }
-         $counter=-1;
-       }
-    }
-    else {
-        sleep 1;
-      if($counter >0){
-         $counter--;
-      }
-       
-      if($counter == 0){
-         $counter=-1;
-         print_( "turn off acter $time_to_power_off_screen_s seconds\n");
-         print_(`$hdmi_off_command`);         
-      }
-    }
+hdmi_off() {
+    tvservice --off
 }
 
-sub print_{
-   print "[".localtime(time) .  "] @_";
+
+hdmi_on() {
+    # get the current state of HDMI output
+    tvservice --status | grep -q HDMI
+    RESULT=$?
+
+    # if HDMI was not found, RESULT=1 ... turn it back on
+    if [ "$RESULT" -eq 1 ] ; then
+       tvservice --preferred
+       fbset -depth 8
+       fbset -depth 16
+       xrefresh
+    fi
 }
+
+# failsafe to make sure monitor stays on in case of quit
+hdmi_on_exit() {
+    interrupt_potential_sleeping_processes
+    rm $TEMPFILE
+    hdmi_on
+    exit
+}
+
+#set -o monitor notify
+#set -bm
+#set +m
+
+trap 'hdmi_on_exit' SIGQUIT SIGINT
+
+hdmi_on
+
+# see fancy process substitution down below
+while read line ; do
+    if [[ $line =~ ^BLANK ]] ; then
+        echo "AAA $line XXX - blank"
+        (
+            sleep 3 
+            hdmi_off
+            echo 0 > $TEMPFILE
+        ) &
+        echo $! > $TEMPFILE
+    fi
+    if [[ $line =~ ^UNBLANK ]] ; then
+        interrupt_potential_sleeping_processes
+        hdmi_on
+    fi
+done < <( xscreensaver-command --watch )
+
+hdmi_on_exit
